"""update tables

Revision ID: 6992307a623c
Revises: c97281d5efb9
Create Date: 2024-12-29 12:03:54.915484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6992307a623c'
down_revision = 'c97281d5efb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
