"""Обнволение модели

Revision ID: ac7615cc7546
Revises: 
Create Date: 2024-12-26 20:47:28.805729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7615cc7546'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('tags',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('images',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('availability')
        batch_op.drop_column('discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('availability', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.alter_column('images',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('tags',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
